### ISSUE TITLE
android.text.SpannedString cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by ganghuaChen** [ufo22940268/android-justifiedtextview#8]
Process: com.zhongduomei.rrmj.society, PID: 23335
    java.lang.ClassCastException: android.text.SpannedString cannot be cast to java.lang.String
            at me.biubiubiu.justifytext.library.JustifyTextView.onDraw(JustifyTextView.java:34)
            at android.view.View.draw(View.java:14493)
            at android.view.View.getDisplayList(View.java:13390)

**Comment by theangi** [comment]
I'm having the same issue, when setting the text with Html.fromHtml() which returns a Spannable object

**Comment by malachid** [comment]
In the onDraw method, changing
```
String text = getText();
```
to
```
String text = getText().toString();
```
seems to fix it.

**Comment by Magenta94** [comment]
Same problem, please release a fixed version.

**Comment by jackyhieu1211** [comment]
remove  android:inputType="textMultiLine" in your xml. it worked good

**Comment by acuna-personal** [comment]
Don't believe that the problem don't fixed yet(

**Comment by Nordis1** [comment]
Learn that[https://www.infopalacess.com/2019/04/justify-text-in-android-studio.html](url)
There is helpful info.
